---
title: "Analysis of funder selectivity"
format: 
  html:
    code-fold: true
  #pdf: default
execute:
  keep-md: true
---

Research questions:
- What is the effect of a funding agency’s level of selectivity on the uptake of data sharing among research teams which allocate their resources strategically?


Approach:

1. Reproduce the below analysis from new simulation file
2. Run across all three types of networks
3. Back up claims by individual data

```{r, echo=FALSE, message=FALSE}
library(sparklyr)
library(patchwork)
library(dplyr)
library(arrow)
library(here)

extrafont::loadfonts()
theme_set(theme_bw(base_family = "Hind"))

source(here("R/functions.R"))

Sys.setenv(SPARK_HOME = "/home/tklebel/spark-3.4.0-bin-hadoop3/")
Sys.setenv(HADOOP_HOME = "/home/hadoop/hadoop-3.3.1")
Sys.setenv(HADOOP_CONF_DIR = "/home/hadoop/hadoop-3.3.1/etc/hadoop")
Sys.setenv(YARN_HOME = "/home/hadoop/hadoop-3.3.1")
Sys.setenv(YARN_CONF_DIR = "/home/hadoop/hadoop-3.3.1/etc/hadoop")
Sys.setenv(JAVA_HOME="/usr/lib/jvm/java-1.11.0-openjdk-amd64")

config <- spark_config()
config$spark.executor.cores <- 5
config$spark.executor.instances <- 20
config$spark.executor.memory <- "20G"

sc <- spark_connect(master = "yarn", config = config,
                    app_name = "funding_selectivity")

df <- spark_read_csv(
  sc, "vary_incentives",
  path = "/tklebel/data_sharing_abm/vary_incentives.csv.bz2",
  memory = TRUE
)

```


# Effect of grant size
```{r fig.width=7, fig.height=9}
pdata <- df %>% 
  filter(step > 0, sharingincentive == .4) %>% 
  group_by(step, fundedshare, maxinitialutility, network) %>% 
  summarise(mean_gini = mean(gini_resources_of_turtles),
            mean_cumulative_gini = mean(gini_totalfunding_of_turtles),
            mean_sharing = mean(sharing)) %>% 
  collect() %>% 
  mutate(maxinitialutility = recode(maxinitialutility, `4` = "Uniform initial sharing effort",
                                      `-4` = "Low initial sharing effort"),
         fundedshare = scales::percent(fundedshare, accuracy = 1))
```


```{r fig.width=7, fig.height=9}
#| label: fig-funder-selectivity
#| fig-cap: Gini index and % of groups sharing data dependent on grant size with no network.
n_row <- 1

no_network <- pdata %>% 
  filter(network == "none")

p1 <- no_network %>%  
  ggplot(aes(step, mean_gini, colour = as.factor(fundedshare))) +
  geom_line() +
  facet_wrap(vars(maxinitialutility), nrow = n_row) +
  labs(colour = "% of teams receiving funding",
       y = "Gini of current resources", x = NULL)

p2 <- no_network %>%  
  ggplot(aes(step, mean_cumulative_gini, colour = as.factor(fundedshare))) +
  geom_line() +
    facet_wrap(vars(maxinitialutility), nrow = n_row) +
    labs(colour = "% of teams receiving funding",
       y = "Gini of total resources",
       x = "Step")

p3 <- no_network %>%  
  ggplot(aes(step, mean_sharing, colour = as.factor(fundedshare))) +
  geom_line() +
  facet_wrap(vars(maxinitialutility), nrow = n_row) +
  labs(colour = "% of teams receiving funding",
       y = "% of teams sharing data", x = NULL) 

p3 / p1 / p2 +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") & theme(legend.position = "top")
```


